### ISSUE TITLE
Typescript complains about "object" in definition

### ISSUE THREAD

**Issue by sebastien-roch** [aurelia/dialog#287]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-rc.1.0.2

**Please tell us about your environment:**
* **Operating System:**
Windows 7

* **Node Version:**
6.9.1

* **NPM Version:**
4.4.4

* **JSPM OR Webpack AND Version**
webpack 2.1.0-beta.27

* **Browser:**
all

* **Language:**
TypeScript 2.1.1

**Current behavior:**
The typescript compiler complains with this error:
``` 
node_modules\aurelia-dialog\dist\commonjs\dialog-settings.d.ts:13:33
Cannot find name 'object'.
```
I guess it's because my version of Typescript is 2.1 and does not support "object" in type definitions.

This is the code triggering the error:
```
viewModel?: string | {
        new (...params: any[]): object;
    } | object;
```
I think the only way to fix that is replacing `object` with `any`? or is there a better alternative?
I can submit a PR to fix this. 

**Expected/desired behavior:**
aurelia-dialog should work with Typescript 2.1, which is not that old...

* **What is the motivation / use case for changing the behavior?**
In some projects it's not possible to upgrade Typescript to the very latest version.

**Comment by StrahilKazlachev** [comment]
Checking what should be the min TS version.

**Comment by StrahilKazlachev** [comment]
For now we are staying TS >=2.2 compliant.
